### ISSUE TITLE
Be transparent that Stardog Community does not support Virtual Graph.

### ISSUE THREAD

**Issue by jpmfribeiro** [stardog-union/stardog-docs#101]
I suggest writing in the Virtual Graph section as the first thing a note like:
_NOTE: Virtual Graph is only supported in Stardog Enterprise._

Another idea would be to support it in Stardog Community also. Then you don't need 
to change the docs...

**Comment by kendall** [comment]
Thanks for the feedback. We will update the docs with a list of what isn't supported in Stardog Community for the next release.

**Comment by BartPraats** [comment]
Did you guys already include it somewhere? I couldn't find it and have been struggling the past days with the VIRTUAL keyword. Until I found this post yesterday...

**Comment by kendall** [comment]
Will be updated for the upcoming 5.0 release; this fell thru the cracks previously.
