### ISSUE TITLE
archived docs have incorrect links

### ISSUE THREAD

**Issue by mhgrove** [stardog-union/stardog-docs#115]
for example, for [man pages](http://docs.stardog.com/4.1.3/#_man_pages) those link back to the man pages for the current version. same with release notes, javadocs

**Comment by mhgrove** [comment]
the same goes for the css, which for now is ok since we don't change that really between versions, but if we ever did a redesign of any significance, older versions of docs could be borked. each copy of the docs should be complete self contained

**Comment by kendall** [comment]
fixed for 5.0
