### ISSUE TITLE
link awesome query plan blog post from docs?

### ISSUE THREAD

**Issue by joernhees** [stardog-union/stardog-docs#120]
Even though i'm familiar with query plans from mysql, postgres, jena, virtuoso, rdflib, ... i recently tried to analyze a plan for a pretty complicated query on a small dataset in stardog...

In what in hindsight i don't see as my proudest moment, the `[#1]` and `[#75]` triggered "issue references" in my brain, so i was moderately confused how these references in the tree output worked. :joy: I remember briefly trying to look this up in your docs in the [query explain section], but not finding anything that explains the output.

Today i was then pointed to this nice blog post: https://blog.stardog.com/how-to-read-stardog-query-plans/ . I thought "ah yepp, with those queries (and numbers like `[#17.7M]` or `[#433K]`) it's pretty obvious".

The post explains a lot more than just the (now) obvious cardinality estimates like pipeline breakers (and the implications of HashJoin vs MergeJoin, ...), skipping (with Scan), Filter(?v1=?v2), etc. Would be cool if you added that link to the [query explain section] for other future dummies like me ;)

[query explain section]: https://docs.stardog.com/man/query-explain.html

**Comment by kendall** [comment]
Yes, we will be doing something like this for the upcoming Stardog 5.0 release's docs. That blog post will be a section in the docs about how to interpret our query plans. Thanks for the feedback!

**Comment by kendall** [comment]
Sorry, I should have looked at this more carefully. We already did put that blog post into the docs, so a search of our docs for "query plan" would have turned that up. See https://docs.stardog.com/#_managing_query_performance.
